server.port=${PORT:${SERVER_PORT:8087}}
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}

blockchain.node-url=${BLOCKCHAIN_NODE_URL}
blockchain.private-key=${BLOCKCHAIN_PRIVATE_KEY}
blockchain.contract-address=${BLOCKCHAIN_CONTRACT_ADDRESS}
blockchain.chain-id=${BLOCKCHAIN_CHAIN_ID:11155111}

muni.internal.token=${MUNI_INTERNAL_TOKEN}
