services:
  app-validacion:
    build: .
    container_name: app-validacion
    restart: unless-stopped
    ports:
      - "8089:8089"
    environment:
      MUNI_DOCUMENTOS_URL: ${MUNI_DOCUMENTOS_URL:-http://app-documentos:8088/documentos}
      MUNI_BLOCKCHAIN_URL: ${MUNI_BLOCKCHAIN_URL:-http://app-blockchain:8087/api/blockchain}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - muni-network

networks:
  muni-network:
    external: true
