-- =============================================
-- V20260428174500: Crear tabla de territorios
-- =============================================

CREATE TABLE territorios (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(150)    NOT NULL,
    tipo            VARCHAR(50),
    numero_unidad_vecinal VARCHAR(20),
    comuna          VARCHAR(100)    NOT NULL,
    region          VARCHAR(100)    NOT NULL,
    direccion_sede  VARCHAR(200),
    latitud         DOUBLE PRECISION,
    longitud        DOUBLE PRECISION,
    limite_norte    VARCHAR(200),
    limite_sur      VARCHAR(200),
    limite_este     VARCHAR(200),
    limite_oeste    VARCHAR(200),
    email           VARCHAR(150),
    telefono        VARCHAR(20),
    presidente      VARCHAR(150),
    descripcion     VARCHAR(1000),
    activo          BOOLEAN         NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP,
    ultima_actualizacion TIMESTAMP
);
