-- =============================================
-- V20260428174600: Crear tabla de usuarios
-- =============================================

CREATE TABLE usuarios (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres             VARCHAR(80)     NOT NULL,
    apellido_paterno    VARCHAR(80)     NOT NULL,
    apellido_materno    VARCHAR(80),
    rut                 VARCHAR(20)     NOT NULL,
    fecha_nacimiento    DATE,
    genero              VARCHAR(20),
    email               VARCHAR(150)    NOT NULL,
    telefono            VARCHAR(20),
    direccion           VARCHAR(200),
    comuna              VARCHAR(100),
    region              VARCHAR(100),
    password            VARCHAR(255)    NOT NULL,
    rol                 VARCHAR(30)     NOT NULL,
    activo              BOOLEAN         NOT NULL DEFAULT TRUE,
    territorio_id       BIGINT,
    fecha_registro      TIMESTAMP,
    ultima_actualizacion TIMESTAMP,

    CONSTRAINT uk_usuarios_rut   UNIQUE (rut),
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT fk_usuarios_territorio
        FOREIGN KEY (territorio_id) REFERENCES territorios (id)
);
