server.port=${PORT:${SERVER_PORT:8090}}
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}

# Configuración de correo para Producción
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT:25}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS_ENABLE:true}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

# Seguridad JWT
jwt.secret=${JWT_SECRET}

muni.internal.token=${MUNI_INTERNAL_TOKEN}
