spring.application.name=api-gateway
server.port=${PORT:${SERVER_PORT:8080}}

# Registro con Eureka Server
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# --- Rutas de Gateway usando Eureka ---
# Ruta Servicio Usuarios
spring.cloud.gateway.routes[0].id=usuarios-route
spring.cloud.gateway.routes[0].uri=lb://usuarios
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**, /usuarios/**, /territorios/**

# Ruta Servicio Blockchain
spring.cloud.gateway.routes[1].id=blockchain-route
spring.cloud.gateway.routes[1].uri=lb://blockchain
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/blockchain/**

# Ruta Servicio Documentos
spring.cloud.gateway.routes[2].id=documentos-route
spring.cloud.gateway.routes[2].uri=lb://documentos
spring.cloud.gateway.routes[2].predicates[0]=Path=/documentos/**

# Ruta Servicio Validación
spring.cloud.gateway.routes[3].id=validacion-route
spring.cloud.gateway.routes[3].uri=lb://Validacion
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/validacion/**

# --- Configuración global de CORS para permitir peticiones del Frontend ---
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=Authorization,Content-Type,X-Internal-Token
