server.port=${PORT:${SERVER_PORT:8086}}
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}

# --- PostgreSQL Prod ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# --- JWT Prod Secret ---
jwt.secret=${JWT_SECRET}
