spring.application.name=documentos
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# --- JPA / Hibernate Common ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Flyway ---
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# --- Resilience4j Circuit Breaker Config ---
resilience4j.circuitbreaker.instances.blockchainCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.blockchainCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.blockchainCB.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.blockchainCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.blockchainCB.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.notificacionCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.notificacionCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificacionCB.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.notificacionCB.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.notificacionCB.automatic-transition-from-open-to-half-open-enabled=true

