server.port=${PORT:${SERVER_PORT:8088}}
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}

# --- PostgreSQL Prod ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# --- Microservices Integration Prod ---
muni.usuarios.url=${MUNI_USUARIOS_URL}
muni.territorios.url=${MUNI_TERRITORIOS_URL}
muni.notificacion.url=${MUNI_NOTIFICACION_URL:http://notificacion.railway.internal:8090/api/notificaciones/public}
muni.internal.token=${MUNI_INTERNAL_TOKEN}

# --- JWT Prod Secret ---
jwt.secret=${JWT_SECRET}

# --- Blockchain Integration URL ---
muni.blockchain.url=${MUNI_BLOCKCHAIN_URL}
