server.port=8088

# --- PostgreSQL Dev ---
spring.datasource.url=jdbc:postgresql://localhost:5433/documentos_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

# --- Microservices Integration Dev ---
muni.usuarios.url=http://localhost:8086/usuarios
muni.territorios.url=http://localhost:8086/territorios
muni.internal.token=muni-digital-secret-token-2024

# --- JWT Dev Secret ---
jwt.secret=bXVuaS1kaWdpdGFsLXNlY3JldC1rZXktMjAyNC1zZWN1cmUtand0LXRva2Vu

# --- Blockchain Integration URL ---
muni.blockchain.url=http://localhost:8087/api/blockchain
