server.port=0

# --- PostgreSQL Test ---
spring.datasource.url=jdbc:postgresql://localhost:5433/documentos_test
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop

muni.usuarios.url=http://localhost:8086/usuarios
muni.territorios.url=http://localhost:8086/territorios
muni.internal.token=muni-digital-secret-token-2024
jwt.secret=dGVzdC1zZWNyZXQta2V5LXRlc3Qtc2VjcmV0LWtleS10ZXN0LXNlY3JldA==
muni.blockchain.url=http://localhost:8087/api/blockchain
