server.port=${PORT:${SERVER_PORT:8089}}
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}

# --- Microservices Integration Prod ---
muni.documentos.url=${MUNI_DOCUMENTOS_URL}
muni.blockchain.url=${MUNI_BLOCKCHAIN_URL}
