server.port=${PORT:${SERVER_PORT:8089}}
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}

# --- Microservices Integration Prod ---
muni.documentos.url=${MUNI_DOCUMENTOS_URL:http://documentos.railway.internal:8080/documentos}
muni.blockchain.url=${MUNI_BLOCKCHAIN_URL:http://blockchain.railway.internal:8080/api/blockchain}
