-- Migración inicial: Creación de tablas para Documentos

CREATE TABLE documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descripcion TEXT,
    estado VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    firmado_por VARCHAR(255),
    firma_digital TEXT,
    hash_sha256 VARCHAR(64),
    codigo_qr_url VARCHAR(500),
    ruta_archivo_pdf VARCHAR(255),
    estado_blockchain VARCHAR(255),
    blockchain_tx_hash VARCHAR(255)
);

CREATE TABLE documentos_jjvv (
    id BIGINT PRIMARY KEY REFERENCES documentos(id),
    junta_vecinos_id BIGINT,
    nombre_junta_vecinal VARCHAR(255),
    tipo_acta VARCHAR(255) NOT NULL,
    rut_ministro_fe VARCHAR(255)
);

CREATE TABLE documentos_licitacion (
    id BIGINT PRIMARY KEY REFERENCES documentos(id),
    codigo_licitacion VARCHAR(255) NOT NULL,
    tipo_licitacion VARCHAR(255) NOT NULL,
    proyecto_id BIGINT,
    fecha_apertura DATE,
    fecha_cierre DATE
);

CREATE TABLE documentos_contrato (
    id BIGINT PRIMARY KEY REFERENCES documentos(id),
    rut_contratista VARCHAR(255) NOT NULL,
    monto_total DOUBLE PRECISION,
    licitacion_asociada_id BIGINT,
    fecha_inicio_contrato DATE,
    fecha_termino_contrato DATE
);

CREATE TABLE documentos_salvoconducto (
    id BIGINT PRIMARY KEY REFERENCES documentos(id),
    usuario_id BIGINT,
    usuario_nombre_completo VARCHAR(255),
    usuario_rut VARCHAR(255),
    motivo TEXT,
    direccion_destino VARCHAR(255),
    fecha_vencimiento TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE documentos_residencia (
    id BIGINT PRIMARY KEY REFERENCES documentos(id),
    usuario_id BIGINT NOT NULL,
    usuario_nombre_completo VARCHAR(255),
    usuario_rut VARCHAR(255),
    usuario_direccion VARCHAR(255),
    usuario_comuna VARCHAR(255)
);
